POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "The existing code and tests need to be changed when user is added to system",
  "important": false,
  "userId": "64a55e648812cff939903c2a"
}